name: deploy-to-heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create .env
        env:
          MAIL_SEND_URL: ${{ secrets.MAIL_SEND_URL }}
          MAIL_SEND_KEY: ${{ secrets.MAIL_SEND_KEY }}
        run: |
          echo mailSendURL=$MAIL_SEND_URL >> .env
          echo mailSendKey=$MAIL_SEND_KEY >> .env
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
